In [1]:
import numpy as np 

In [2]:
one = np.array([1,2,6,7,3,4,90])

In [3]:
one 

array([ 1,  2,  6,  7,  3,  4, 90])

In [4]:
one.argmax()

np.int64(6)

In [5]:
one.argmin()

np.int64(0)

In [6]:
one.argsort()

array([0, 1, 4, 5, 2, 3, 6])

In [7]:
one

array([ 1,  2,  6,  7,  3,  4, 90])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [15]:
arr.argmin()

np.int64(8)

In [17]:
arr.argmax()

np.int64(6)

In [18]:
arr.argmax(axis=0)

array([2, 1, 1])

In [19]:
arr.argmax(axis=1)

array([2, 2, 0])

In [21]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [22]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [23]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [25]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [26]:
arr+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [28]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [29]:
arr*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [31]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [32]:
np.sqrt(9)

np.float64(3.0)

In [33]:
arr.sum()

np.int64(29)

In [34]:
arr.max()

np.int64(7)

In [35]:
arr.min()

np.int64(0)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
arr.sort()

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [39]:
np.where(arr>5)

(array([1, 2]), array([2, 2]))

In [40]:
type(np.where(arr>5))

tuple

In [41]:
np.count_nonzero(arr)

np.int64(8)

In [42]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 1, 2]))

In [43]:
import  sys

In [44]:
py_ar = [0,4,55,2]

In [45]:
np_ar =np.array(py_ar)

In [46]:
sys.getsizeof(1)*len(py_ar)

112

In [47]:
np_ar.itemsize*np_ar.size

32

In [49]:
arr.tolist()

[[1, 2, 3], [4, 5, 6], [0, 1, 7]]